language: android
dist: trusty
sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - tools
before_install:
 - yes | sdkmanager "platforms;android-28"
 - echo y | android update sdk -u -a -t build-tools-27.0.3
before_script:
  - curl https://kaltura.github.io/fe-tools/android/license.sh | sh
script:
  - ./gradlew kavaplugin:build
after_failure:
  - cat kavaplugin/build/outputs/lint-results-debug.xml
after_success:
  - ./travis-push-to-bintray.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: always
    on_failure: always
